CREATE OR REPLACE TABLE DAILY_ACCOUNT_BALANCE AS
SELECT
    ACCOUNT_ID,
    TRANSACTION_DATE,
    SUM(
        CASE 
            WHEN TRANSACTION_TYPE = 'CREDIT' THEN AMOUNT
            ELSE -AMOUNT
        END
    ) AS DAILY_BALANCE
FROM TRANSACTION
GROUP BY ACCOUNT_ID, TRANSACTION_DATE;