CREATE OR REPLACE TABLE MONTHLY_CUSTOMER_SUMMARY AS
SELECT
    C.CUSTOMER_ID,
    DATE_TRUNC('MONTH', T.TRANSACTION_DATE) AS MONTH,
    COUNT(T.TRANSACTION_ID) AS TOTAL_TRANSACTIONS,
    SUM(T.AMOUNT) AS TOTAL_AMOUNT
FROM CUSTOMER C
JOIN ACCOUNT A ON C.CUSTOMER_ID = A.CUSTOMER_ID
JOIN TRANSACTION T ON A.ACCOUNT_ID = T.ACCOUNT_ID
GROUP BY C.CUSTOMER_ID, DATE_TRUNC('MONTH', T.TRANSACTION_DATE);